name: Run Tests On Push
on:
  push:
  pull_request:
env:

  ENV: testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install dependencies
        working-directory: ./
        run: |
          pip install -r requirements.txt
          echo requirements installed

      - name: Set OPENAI_API_KEY
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m unittest UnitTesting/test_app.py
